_target_: src.models.masksembles_module.MasksemblesModule

input_size: 784
lin1_size: 256
lin2_size: 256
lin3_size: 256
output_size: 10
lr: 0.001
weight_decay: 0.0005
dropout: 0.0
num_in: 
num_out: 
activ: nn.PReLU()
dropout:
batch_norm:
kernel: 
stride: 
pad: 